baseURL: https://heewen.netlify.app/
languageCode: en-us
title: Portfolio Website for Hee Wen Loo
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
  #  subtitle: |-
    #  A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
     # AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Hee Wen!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 24 Apple Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: hloo.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 123-4567
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description abc
 # error404:
  #  heading: Page couldn't be found
   # text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
    # label: Twitter
      #  url: https://www.twitter.com
      #- icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/heewen.loo.9/
      -# icon: fa-instagram
       # label: Instagram
        #url: https://www.instagram.com
    #  - icon: fa-github
     #   label: GitHub
      #  url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/hee-wen-l-4b6066196/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
  #  button2:
   #   - name: Log In
    #    url: '#'
    links:
      - name: Home
        url: '#'
    #  - name: Blogs
     #   url: blogs
    #  - name: Generic Blog
     #   url: blogs/ipsum
   #   - name: Elements
    #    url: elements.html
    menu: Menu
    subtitle: By Hee 
    title: Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: About me.jpg
        subtitle: Introduction of Myself 
        title: About Me
        url: blogs/profile
      - image: lbs.jpg
        subtitle: R Markdown Practice
        title: Pre-Program Assignment
        url: blogs/Hee-Wen-Loo_pre_programme_assignment
      - image: spices.jpg
        subtitle: Risk Return Example from Kostis
        title: Risk Return of DJIA Stocks
        url: blogs/risk_return
      - image: one.jpg
        subtitle: 1st R Group Assignment
        title: Homework 1
        url: blogs/homework_1
      - image: two.jpg
        subtitle: 2nd R Group Assignment
        title: Homework 2
        url: blogs/ipsum
      - image: three.jpg
        subtitle: 3rd R Group Assignment
        title: Homework 3
        url: blogs/homework_3
 # two:
#    buttonText: Get Started!
 #   enable: yes
  #  subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
   #   \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
    #  condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
     # pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      #Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      #amet pharetra et feugiat tempus."
    #title: Massa libero
    #url: blogs
